// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2UbTO1voIVIDMt1AWbpi2MLnHtMm5U40',
    appId: '1:221774097926:web:e4d7fe4df69cc329021d87',
    messagingSenderId: '221774097926',
    projectId: 'buoi11-5527e',
    authDomain: 'buoi11-5527e.firebaseapp.com',
    storageBucket: 'buoi11-5527e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_A6G04F7A1GbXo1tP39txcTs7SmGHPM',
    appId: '1:221774097926:android:cba84d3188064383021d87',
    messagingSenderId: '221774097926',
    projectId: 'buoi11-5527e',
    storageBucket: 'buoi11-5527e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQIcJQPPJoEAH2zd_VAQPYEU_e06XQuPc',
    appId: '1:221774097926:ios:cd1ce64d2fbd1e9f021d87',
    messagingSenderId: '221774097926',
    projectId: 'buoi11-5527e',
    storageBucket: 'buoi11-5527e.firebasestorage.app',
    androidClientId: '221774097926-bnuva7i2rttl6dlq1smjv01219gc0kb3.apps.googleusercontent.com',
    iosClientId: '221774097926-a7nukl57i1fnaaomgqokd9h1sn8ih78a.apps.googleusercontent.com',
    iosBundleId: 'com.example.lovehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQIcJQPPJoEAH2zd_VAQPYEU_e06XQuPc',
    appId: '1:221774097926:ios:cd1ce64d2fbd1e9f021d87',
    messagingSenderId: '221774097926',
    projectId: 'buoi11-5527e',
    storageBucket: 'buoi11-5527e.firebasestorage.app',
    androidClientId: '221774097926-bnuva7i2rttl6dlq1smjv01219gc0kb3.apps.googleusercontent.com',
    iosClientId: '221774097926-a7nukl57i1fnaaomgqokd9h1sn8ih78a.apps.googleusercontent.com',
    iosBundleId: 'com.example.lovehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2UbTO1voIVIDMt1AWbpi2MLnHtMm5U40',
    appId: '1:221774097926:web:31e4c77eea2acff8021d87',
    messagingSenderId: '221774097926',
    projectId: 'buoi11-5527e',
    authDomain: 'buoi11-5527e.firebaseapp.com',
    storageBucket: 'buoi11-5527e.firebasestorage.app',
  );
}
